export const SAVE_CLASS_ERROR = 'SAVE_CLASS_ERROR';
export const SAVE_CLASS_SUCCESS = 'SAVE_CLASS_SUCCESS';
export const FETCH_CLASS = 'FETCH_CLASS';
export const UPDATE_SCHOOL_SUCCESS = 'UPDATE_SCHOOL_SUCCESS';
export const UPDATE_SCHOOL_ERROR = 'UPDATE_SCHOOL_ERROR';
