export const CREATE_CLASS_PROFILE_SUCCESS = 'CREATE_CLASS_PROFILE_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS ';
export const CLEAR_FEEDBACK = 'CLEAR_FEEDBACK';
