export const CREATE_CLASS_PROFILE_SUCCESS = 'CREATE_CLASS_PROFILE_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS ';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CLEAR_FEEDBACK = 'CLEAR_FEEDBACK';
export const CREATE_CLASS_PROFILE_ERROR = 'CREATE_CLASS_PROFILE_ERROR';
export const UPDATE_ERROR = 'UPDATE_ERROR';
