export const CREATE_TEACHER_SUCCESS = 'CREATE_TEACHER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS ';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CLEAR_FEEDBACK = 'CLEAR_FEEDBACK';
export const CREATE_TEACHER_ERROR = 'CREATE_TEACHER_ERROR';
export const UPDATE_ERROR = 'UPDATE_ERROR';
export const UPDATE_TEACHER_SUCCESS = 'UPDATE_TEACHER_SUCCESS';

