export const CREATE_TEACHER_SUCCESS = 'CREATE_TEACHER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS ';
export const UPDATE_TEACHER_SUCCESS = 'UPDATE_TEACHER_SUCCESS';

